
In this notebook, we look at quantum
operators, sets, vectors, matrices, and tensors. These are the mathematical concepts required for quantum computing.

Then for the basics we look at single and multiple quantum bit systems. Quantum bits system phenomena such as entanglement, superposition, and teleportation and finally, the quantum states, gates, and transformations are presented.

In [3]:
# quantum_operations.py 

import numpy as nump 

def multi_quantum_state(*args):
    ret = nump.array([[1.0]])
    for q in args:
        ret = nump.kron(ret, q)
    return ret

zero_quantum_state = nump.array([[1.0], [0.0]]) 

one_quantum_state = nump.array([[0.0], [1.0]]) 

Hadmard_quantum_gate = 1.0 / 2**0.5 * nump.array([[1, 1], [1, -1]]) 

new_quantum_state = nump.dot(Hadmard_quantum_gate, zero_quantum_state) 
print("dot product : Hadamard quantum gate and zero quantumstate",new_quantum_state) 

SWAP_quantum_gate = nump.array([[1,0,0,0],
                      [0,0,1,0],
                      [0,1,0,0],
                      [0,0,0,1]]) 

t0_quantum_state = multi_quantum_state(zero_quantum_state, one_quantum_state) 
t1_quantum_state = nump.dot(SWAP_quantum_gate, t0_quantum_state) 
print("SWAP Quantum Gate - T1 Quantum state",t1_quantum_state)

Identity_quantum_gate = nump.eye(2)
t0_quantum_state = multi_quantum_state(zero_quantum_state, one_quantum_state) 
t1_quantum_state = nump.dot(multi_quantum_state(Hadmard_quantum_gate, Identity_quantum_gate), t0_quantum_state) 
print("Multi Quantum State of H Quantum gate and I Quantum gate",t1_quantum_state)

dot product : Hadamard quantum gate and zero quantumstate [[0.70710678]
 [0.70710678]]
SWAP Quantum Gate - T1 Quantum state [[0.]
 [0.]
 [1.]
 [0.]]
Multi Quantum State of H Quantum gate and I Quantum gate [[0.        ]
 [0.70710678]
 [0.        ]
 [0.70710678]]


In [ ]:
# Set operations
primes11={3,5,7,11,14}; 
primes12={3,5,7,11,13,17,19,34} 
primes=primes11 & primes12 
print("union of sets", primes11,",",primes12," is") 
print(primes)

union of sets {3, 5, 7, 11, 14} , {34, 3, 5, 7, 11, 13, 17, 19}  is
{11, 3, 5, 7}


In [ ]:
primes1={3,5,7,11,13}; 
primes2={3,5,7,11,13,17,19,23} 
primes=primes1 & primes2 
print("intersection of sets", primes1,",", primes2," is") 
print(primes)

intersection of sets {3, 5, 7, 11, 13} , {3, 5, 7, 11, 13, 17, 19, 23}  is
{3, 5, 7, 11, 13}


In [ ]:
primes3={3,5,7,11,13,17,19} 
primes4={2,3,5,7,11}; 
primes=primes3-primes4 
print("difference of sets",primes3,",",primes4," is") 
print(primes)

difference of sets {3, 5, 7, 11, 13, 17, 19} , {2, 3, 5, 7, 11}  is
{17, 19, 13}


In [ ]:
primes4={3,5,7,11,13,17,19} 
primes5={3,5,7,11,91,101}; 
primes=primes4 ^ primes5 
print("symmetric difference of sets",primes4,",",primes5," is") 
print(primes)

symmetric difference of sets {3, 5, 7, 11, 13, 17, 19} , {3, 5, 101, 7, 11, 91}  is
{17, 19, 101, 91, 13}


In [ ]:
#vector_operations.py 
from numpy import array 
vector1 = array([1, 2, 3]) 
vector2 = array([2, 3, 4]) 
print("dot product of", vector1,", ",vector2,"is") 
product = vector1.dot(vector2) 
print(product) 
scalarval = 0.3 
scalarprod = scalarval*vector1 
print("scalar multiplied",scalarval,",",vector1,"is")
print(scalarprod) 
print("sum of", vector1,", ",vector2,"is") 
sum = vector1 + vector2 
print(sum) 
print("difference of", vector1,", ",vector2,"is")
diff = vector1 - vector2 
print(diff) 
print("product of", vector1,", ",vector2,"is") 
prod = vector1 * vector2 
print(prod) 
print("division of", vector1,", ",vector2,"is") 
dividedby = vector1 / vector2 
print(dividedby)

dot product of [1 2 3] ,  [2 3 4] is
20
scalar multiplied 0.3 , [1 2 3] is
[0.3 0.6 0.9]
sum of [1 2 3] ,  [2 3 4] is
[3 5 7]
difference of [1 2 3] ,  [2 3 4] is
[-1 -1 -1]
product of [1 2 3] ,  [2 3 4] is
[ 2  6 12]
division of [1 2 3] ,  [2 3 4] is
[0.5        0.66666667 0.75      ]


In [ ]:
#matrix_operations.py 
#import numpy 
mat1 = nump.array([[1, 3], [4, 6]]) 
mat2 = nump.array([[7, 9], [11, 15]]) 
print ("Addition of matrices ", mat1,",", mat2,"is") 
print (nump.add(mat1,mat2)) 
print ("Subtraction of matrices ", mat1,",", mat2,"is") 
print (nump.subtract(mat1,mat2)) 
print ("Product of matrices ", mat1,",", mat2,"is")
print (nump.multiply(mat1,mat2)) 
print ("Dot Product of matrices ", mat1,",", mat2,"is") 
print (nump.dot(mat1,mat2)) 
print ("Division of matrices ", mat1,",", mat2,"is") 
print (nump.divide(mat1,mat2))
print ("Transpose of ", mat1,"is") 
print (mat1.T)

Addition of matrices  [[1 3]
 [4 6]] , [[ 7  9]
 [11 15]] is
[[ 8 12]
 [15 21]]
Subtraction of matrices  [[1 3]
 [4 6]] , [[ 7  9]
 [11 15]] is
[[-6 -6]
 [-7 -9]]
Product of matrices  [[1 3]
 [4 6]] , [[ 7  9]
 [11 15]] is
[[ 7 27]
 [44 90]]
Dot Product of matrices  [[1 3]
 [4 6]] , [[ 7  9]
 [11 15]] is
[[ 40  54]
 [ 94 126]]
Division of matrices  [[1 3]
 [4 6]] , [[ 7  9]
 [11 15]] is
[[0.14285714 0.33333333]
 [0.36363636 0.4       ]]
Transpose of  [[1 3]
 [4 6]] is
[[1 4]
 [3 6]]


In [ ]:
#tensor_operations.py 
from numpy import array 
from numpy import tensordot 
tensor1 = array([ [[1,2,3], [4,5,6], [7,8,9]], [[13,12,13], [14,15,16], [17,18,19]], [[24,22,23], [24,25,26], [27,28,29]], ]) 
tensor2 = array([ [[1,4,3], [4,5,6], [7,8,9]], [[11,13,13], [14,15,16], [17,18,19]], [[21,25,23], [24,26,26], [27,28,29]], ])
print("tensor1",tensor1) 
print("tensor2",tensor2) 
print("sum of tensors", "is") 
sum = tensor1 + tensor2 
print(sum) 
print("difference of tensors", "is") 
diff = tensor1 - tensor2
print(diff) 
print("product of tensors", "is") 
prod = tensor1 * tensor2 
print(prod) 
print("division of tensors", "is") 
division = tensor1 / tensor2
print(division) 
print("dot product of tensors", "is") 
dotproduct = tensordot(tensor1, tensor2, axes=0) 
print(dotproduct)

tensor1 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[13 12 13]
  [14 15 16]
  [17 18 19]]

 [[24 22 23]
  [24 25 26]
  [27 28 29]]]
tensor2 [[[ 1  4  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 13 13]
  [14 15 16]
  [17 18 19]]

 [[21 25 23]
  [24 26 26]
  [27 28 29]]]
sum of tensors is
[[[ 2  6  6]
  [ 8 10 12]
  [14 16 18]]

 [[24 25 26]
  [28 30 32]
  [34 36 38]]

 [[45 47 46]
  [48 51 52]
  [54 56 58]]]
difference of tensors is
[[[ 0 -2  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 2 -1  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 3 -3  0]
  [ 0 -1  0]
  [ 0  0  0]]]
product of tensors is
[[[  1   8   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[143 156 169]
  [196 225 256]
  [289 324 361]]

 [[504 550 529]
  [576 650 676]
  [729 784 841]]]
division of tensors is
[[[1.         0.5        1.        ]
  [1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[1.18181818 0.92307692 1.        ]
  [1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[1.14285714 0.88       1. 

The Basics

In [ ]:
#single_qubit_system.py 
import numpy as nump
import scipy as scip 
import scipy.linalg 
Zero_state = nump.array([[1.0], [0.0]]) 
One_state = nump.array([[0.0], [1.0]]) 
NormalizeQuantumState = lambda quantum_state: quantum_state / scip.linalg.norm(quantum_state)

Plus_State = NormalizeQuantumState(Zero_state + One_state) 
print("normalized quantum state of",Zero_state, "+", One_state,"is", Plus_State)

normalized quantum state of [[1.]
 [0.]] + [[0.]
 [1.]] is [[0.70710678]
 [0.70710678]]


In [ ]:
#superposition.py 
import numpy as nump 
zero_quantum_state = nump.array([[1.0], [0.0]])
one_quantum_state = nump.array([[0.0], [1.0]]) 
quantum_amp1 = 1.0 / 2**0.5 
quantum_amp2 = 1.0 / 2**0.5 
superposition_quantum_state = quantum_amp1 * zero_quantum_state + quantum_amp2 * one_quantum_state
print("superposition of", zero_quantum_state, " and ", one_quantum_state," is ",superposition_quantum_state)

superposition of [[1.]
 [0.]]  and  [[0.]
 [1.]]  is  [[0.70710678]
 [0.70710678]]


In [8]:
#Multi_Qubit_System.py
import math 
import random 

def ApplyCNOTQuantumGate(zerozero,zeroone,onezero,oneone):
    onezero, oneone = oneone, onezero
    return GetQuantumbits(zerozero,zeroone,onezero,oneone) 

def ApplyHQuantumGate(zerozero,zeroone,onezero,oneone):
    a = zerozero
    b = zeroone
    c = onezero
    d = oneone

    zerozero = a + c
    zeroone = b + d
    onezero = a - c
    oneone = b - d

    normalize()

    return GetQuantumbits(zerozero,zeroone,onezero,oneone)

def ApplyXQuantumGate(zerozero,zeroone,onezero,oneone):
    a = zerozero
    b = zeroone
    c = onezero
    d = oneone

    zerozero = c
    zeroone = d
    onezero = a
    oneone = b

    return GetQuantumbits(zerozero,zeroone,onezero,oneone) 

def ApplyZQuantumGate(zerozero,zeroone,onezero, oneone):
    onezero *= -1
    oneone *= -1

    return GetQuantumbits(zerozero,zeroone,onezero,oneone) 

def ApplyNormalization(zerozero,zeroone,onezero,oneone):
    norm = (abs(zerozero)**2 + abs(zeroone)**2 +
            abs(onezero)**2 + abs(oneone)**2) ** 0.5
    zerozero /= norm
    zeroone /= norm
    onezero /= norm
    oneone /= norm
    return GetQuantumbits(zerozero,zeroone,onezero,oneone)

def MeasureQuantumbit(zerozero,zeroone,onezero,oneone):
    zerozeroprob = abs(zerozero) ** 2
    zerooneprob = abs(zeroone) ** 2
    onezeroprob = abs(onezero) ** 2
    randomchoice = random.random()

    if randomchoice < zerozeroprob:
       zerozero = complex(1)
       zeroone = complex(0)
       onezero = complex(0)
       oneone = complex(0)
       return (0, 0)

    elif randomchoice < zerooneprob:
       zerozero = complex(0)
       zeroone = complex(1)
       onezero = complex(0)
       oneone = complex(0)
       return (0, 1)

    elif randomchoice < onezeroprob:
       zerozero = complex(0)
       zeroone = complex(0)
       onezero = complex(1)
       oneone = complex(0)
       return (1, 0)

    else:
       zerozero = complex(0)
       zeroone = complex(0)
       onezero = complex(0)
       oneone = complex(1)
       return (1, 1)

def GetQuantumbits(zerozero,zeroone,onezero,oneone):
    comp = [zerozero, zeroone, onezero, oneone]
    comp = [i.real if i.real == i else i for i in comp]
    comp = [str(i) for i in comp]
    comp = ["" if i == "1.0" else i for i in comp]

    ls = []
    if abs(zerozero) > 0:
       ls += [comp[0] + " |00>"]
    if abs(zeroone) > 0:
       ls += [comp[1] + " |01>"]
    if abs(onezero) > 0:
       ls += [comp[2] + " |10>"]
    if abs(oneone) > 0:
       ls += [comp[3] + " |11>"]

    comp = " + ".join(ls)
    return comp 

a_quantum_state = 1
b_quantum_state = 0
c_quantum_state = 0
d_quantum_state = 0
zerozero_quantum_state = complex(a_quantum_state)
zeroone_quantum_state = complex(b_quantum_state)
onezero_quantum_state = complex(c_quantum_state)
oneone_quantum_state = complex(d_quantum_state)
result1 = ApplyCNOTQuantumGate(zerozero_quantum_state,zeroone_quantum_state,onezero_quantum_state,oneone_quantum_state)
print("cnot gate operation - result",result1)
result2 = ApplyXQuantumGate(zerozero_quantum_state,zeroone_quantum_state,onezero_quantum_state,oneone_quantum_state)
print("xgate operation - result",result2) 
result3 = ApplyZQuantumGate(zerozero_quantum_state,zeroone_quantum_state,onezero_quantum_state,oneone_quantum_state)
print("zgate operation - result",result3)
result4 = ApplyNormalization(zerozero_quantum_state,zeroone_quantum_state,onezero_quantum_state,oneone_quantum_state)
print("normalize operation - result",result4)
result5 = MeasureQuantumbit(zerozero_quantum_state,zeroone_quantum_state,onezero_quantum_state,oneone_quantum_state)
print("measure gate operation - result",result5)

cnot gate operation - result  |00>
xgate operation - result  |10>
zgate operation - result  |00>
normalize operation - result  |00>
measure gate operation - result (0, 0)


In [ ]:
#multi_kronecker.py 
import numpy as nump 

def multi_quantum_state(*args):
   ret = nump.array([[1.0]]) 
   for q in args:
       ret = nump.kron(ret, q)
       return ret 

zero_quantum_state = nump.array([[1.0], [0.0]])
one_quantum_state = nump.array([[0.0], [1.0]]) 
three_quantum_states = nump.kron(nump.kron(zero_quantum_state, one_quantum_state), one_quantum_state) 
print("three quantum states -kronecker",three_quantum_states)

three quantum states -kronecker [[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]]
